#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

cookbook 'apt'
cookbook 'mysql', '5.5.3'
cookbook 'sudo'
cookbook 'build-essential'
cookbook 'runit'
cookbook 'git',   '4.1.0'
cookbook 'nginx',         git: "https://gitlab.acid.cl/acidlabs/chef-nginx.git"
cookbook 'openssl'
cookbook 'varnish'
cookbook 'php-fpm'
